### ISSUE TITLE
Is it necessary to provide a minimum config in specs?

### ISSUE THREAD

**Issue by zenlinTechnofreak** [opencontainers/specs#105]
In my developing of [OCT project](https://github.com/huawei-openlab/oct.git), I find that there are some requeired config for the specs item.
For example,
if we want to run a linux container, we should at least containing mount config of proc filesystem, other mounted filesystem is not the necessary one.
``` go
"mounts": [
    {
        "type": "proc",
        "source": "proc",
        "destination": "/proc",
        "options": ""
    },
```

So, I am considering weather we should provid minimum config example or adding some explaining to make notes to the neccesary one?

**Comment by philips** [comment]
Is this the same as https://github.com/opencontainers/specs/issues/95?

**Comment by zenlinTechnofreak** [comment]
@philips Yes, quite nice to see the topic #95 . But I also considering:Should the specs define a minimum set, not only the default one?
My considering is:
Because the specs should be compatible to different OS and Arch, so it just need the minimum set that can make container run, but no only according to any container type.
What is the opinion with you?

**Comment by philips** [comment]
@zenlinTechnofreak I think we should define a minimum set because nearly all applications rely on these filesystem nodes to exist.

**Comment by zenlinTechnofreak** [comment]
@philips Yes, quite agree with u,+1.

**Comment by wking** [comment]
On Mon, Aug 10, 2015 at 08:53:20PM -0700, LinZhinan(Zen Lin) wrote:
> So, I am considering weather we should provid minimal config example…

There are some plans to move the overview docs from runC into this
spec [1].

> … or adding some explaining to make notes to the neccesary one?

It's not machine-readable, but since at least 7ac41c69 (config.md:
reformat into a standard style, 2015-06-30) we've had docs like:

  * **destination** (string, required) …
  * **options** (string, optional) …

for documenting which JSON fields are required and which are optional.
Although we could be more consistent about always declaring that sort
of thing (e.g. it's missing from the device docs, see #101 for an
attempt at covering it there).

[1]: https://github.com/opencontainers/runc/pull/242#discussion_r38484100

**Comment by vbatts** [comment]
#276 also accomplishes this
