### ISSUE TITLE
Copyright owner

### ISSUE THREAD

**Issue by aviau** [opencontainers/specs#147]
Hello!

I am packaging this opencontainers/specs for Debian and I would like to know who is the copyright owner.

It would be a good idea to mention it somewhere.

I noticed that Michael Crosby <crosbymichael@gmail.com> was the one to commit the license.

See: https://github.com/opencontainers/specs/commit/84707b0843db72c7ef4fe476f2bf641b3dac664c

Is he the copyright owner?

//cc @crosbymichael 

Thanks,

**Comment by wking** [comment]
On Thu, Sep 03, 2015 at 03:36:23PM -0700, Alexandre Viau wrote:
> I am packaging this opencontainers/specs for Debian and I would like
> to know who is the copyright owner.

The Developer Certificate of Origin [1] sets things up so that either
contributors still own the copyright for their contribution (under
clause (a)) or they're pulling their contribution from somewhere else
that licenses it appropriately (under clause (b)).  Clause (c) is for
maintainers and other folks in the patch-submission process who each
add their own Signed-off-by clause.  So that means we don't really
know who owns the copyright, and should probably say something like
“The OCI and associated contributors”.

Cheers,
Trevor

[1]: https://github.com/opencontainers/specs/blob/bf52e72391ab34ef8af7afdfb308f0d5beb7c111/README.md#sign-your-work

-- 
This email may be signed or encrypted with GnuPG (http://www.gnupg.org).
For more information, see http://en.wikipedia.org/wiki/Pretty_Good_Privacy

**Comment by wking** [comment]
On Thu, Sep 03, 2015 at 03:54:02PM -0700, W. Trevor King wrote:
> So that means we don't really know who owns the copyright, and
> should probably say something like “The OCI and associated
> contributors”.

But this is just my 2¢.  I'm neither a lawyer nor an OCI member ;).

Cheers,
Trevor

-- 
This email may be signed or encrypted with GnuPG (http://www.gnupg.org).
For more information, see http://en.wikipedia.org/wiki/Pretty_Good_Privacy

**Comment by crosbymichael** [comment]
@aviau Copyright is found towards the bottom of the apache license on this line:

https://github.com/opencontainers/specs/blob/master/LICENSE#L179

Let me know if this is the information you were looking for or if you need to know more about how the DCO comes into play.  

Thanks!

@wking general rule, if you don't know the answer to something, most of the time its better to say nothing than say something wrong and write a disclaimer afterwards.

**Comment by wking** [comment]
On Thu, Sep 03, 2015 at 05:22:27PM -0700, Michael Crosby wrote:
> @aviau Copyright is found towards the bottom of the apache license on this line:
> 
> https://github.com/opencontainers/specs/blob/master/LICENSE#L179

And for folks like me who have seen the DCO frequently, but not had
much experience with the Apache License, the copy-right-assignment
clause is [1].  I guess that means no copy/pasting code from other
projects unless you also have the power to assign copyright for the
code in question ;).

> @wking general rule, if you don't know the answer to something, most
> of the time its better to say nothing than say something wrong and
> write a disclaimer afterwards.

Sorry, I'd intended to make the disclaimer part of the original
comment, but hit send too fast :/.  Hopefully the lag was small enough
to not cause too much uncertainty.

[1]: https://github.com/opencontainers/specs/blob/bf52e72391ab34ef8af7afdfb308f0d5beb7c111/LICENSE#L67-L72

**Comment by wking** [comment]
On Thu, Sep 03, 2015 at 07:00:59PM -0700, W. Trevor King wrote:
> And for folks like me who have seen the DCO frequently, but not had
> much experience with the Apache License, the copy-right-assignment
> clause is [1].
> …
> [1]: https://github.com/opencontainers/specs/blob/bf52e72391ab34ef8af7afdfb308f0d5beb7c111/LICENSE#L67-L72

Ah, more hasty reading on my part :/.  Going back through more
carefully, that section is “Grant of Copyright License” not “Grant of
Copyright”.  That means that the original author still holds copyright
(if the contribution was copyrightable at all [1]).  See also, [2]:

  Though committers retain copyright, Apache asks that they do not add
  copyright statements

And [3]:

  Since contributors maintain their copyright ownership in the works
  they submit, it is misleading to place the ASF copyright at the top
  of each source file.  The previous ASF copyright notice represented
  the ASF's ownership in the collective work of the entire
  distribution, but placing it at the top of each source file was
  causing a lot of confusion.  To avoid this confusion, we are placing
  all copyright notices in a single file and leaving only the
  licensing information within each source file.

So my current guess is that the LF holds “ownership in the collective
work” (whatever that means.  Maybe it means “list them in the Debian
package” ;), while the copyright for contributions is still owned by
the contributors themselves (DOC.a) or someone else that licensed the
contributor to submit the contribution here (DOC.b).  And that's
pretty much what I said in my original post [4].

Also note the caveat at the end of the Apache FAQ [5]:

  Does this policy apply to projects outside the ASF that use the
  Apache License?

  No. This is strictly an ASF policy. Other projects using the Apache
  License should still refer to the license's appendix for guidance on
  applying a header to their source files.

So there's some wiggle room if the LF doesn't agree with Apache's
interpretation.

[1]: http://www.apache.org/legal/src-headers.html#faq-exceptions
[2]: http://apache.org/dev/apply-license.html#contributor-copyright
[3]: http://www.apache.org/legal/src-headers.html#faq-why
[4]: https://github.com/opencontainers/specs/issues/147#issuecomment-137595506
[5]: http://www.apache.org/legal/src-headers.html#faq-nonasf

**Comment by aviau** [comment]
@crosbymichael 
> Let me know if this is the information you were looking for 

Absolutely! I should have noticed. Thank you.
