### ISSUE TITLE
Add a complete oci-bundle example for specs

### ISSUE THREAD

**Issue by ChengTiesheng** [opencontainers/specs#187]
Now, initial draft for OCI specs has been released, so I want to get an oci-bundle to study, and transform it to other container format.
However, I found that there is no complete oci-bundle example to use, and I had to scrabble up an oci-bundle directory through scanning the opencontainers/specs project.
So I think a complete oci-bundle example is needed. oci-bundle example is accompanied by oci specs, and its aim is for the convenience of users.
 
A complete oci-bundle example is something like this:
https://github.com/huawei-openlab/oci2aci/tree/master/example/oci-bundle

**Comment by wking** [comment]
On Mon, Sep 14, 2015 at 08:21:24PM -0700, Tiesheng wrote:
> However, I found that there is no complete oci-bundle example to
> use, and I had to scrabble up an oci-bundle directory through
> scanning the opencontainers/specs project.

I have a few OCI bundles in branches of [1], e.g. [2,3], but I haven't
updated them to match the v0.1.1 spec (or v0.1.0, #183).  They're
2-clause BSD, so feel free to borrow under those terms ;).

I'm less enthusiastic about bundling an example like that into this
repository, since we'd have to pick a platform, vendor some random
binaries compiled elsewhere, etc.  I think it's better to have a few
external repositories with simple things (like my busybox shell [2]),
ideally under github.com/opencontainer/ and link to those.

[1]: https://github.com/wking/oci-gentoo-minimal/
[2]: https://github.com/wking/oci-gentoo-minimal/tree/user-namespace
[3]: https://github.com/wking/oci-gentoo-minimal/tree/ipfs-gateway

**Comment by ChengTiesheng** [comment]
@wking, thanks for your detailed reply. What I want is something like https://github.com/mrunalp/ocitools
When I run oci generate, I can get config.json and runtime.json, but no corresponding rootfs.
So what I exactly need is a tool can generate a complete bundle, including json files and rootfs.

**Comment by wking** [comment]
On Thu, Sep 24, 2015 at 06:42:44PM -0700, Tiesheng wrote:
> When I run oci generate, I can get config.json and runtime.json, but
> no corresponding rootfs.  So what I exactly need is a tool can
> generate a complete bundle, including json files and rootfs.

Generating a rootfs is hard, because there are so many choices.  For
example, this is the section of my Makefile that downloads a Gentoo
stage3 and unpacks the bare minimum needed to run a Go binary with
some cgo linking [1].  That's not much work, but it is a ~200 MB
download (the whole, compressed stage3) for 3.8 MB of unpacked rootfs.
And if you don't trust the Gentoo releng signature, you'll be using
untrusted binaries.  So I don't think my “grab stuff from a stage3”
approach is going to be everyone's cup of tea.  But those are problems
without an easy solution.  For example, if someone grabbed files from
a Debian release to populate a rootfs, you'd need to trust the Debian
releng signature (or however they sign their packages/releases).  And
maybe you need more from your distribution than just ld, libc, and
libpthread?  Or maybe you want musl and not glibc?

If folks intend to use OCI bundles directly (instead of through
higher-level tools like Docker), I think it's probably best to have
folks publish generic templates like my oci-gentoo-minimal master
branch, and then have folks who don't want to get into that just pick,
for example, someone else's popular BusyBox template (or whatever) for
their project.

[1]: https://github.com/wking/oci-gentoo-minimal/blob/5f6850f05a4c183434cdb77774b10c9719649d49/Makefile#L18-L25

**Comment by ChengTiesheng** [comment]
Solved, thanks.
