### ISSUE TITLE
tooling: basic validation tool for config.json

### ISSUE THREAD

**Issue by philips** [opencontainers/specs#43]
We should wait until the first "draft" is done so we don't rewrite it all the time :)

Basic operation:

- octool lint <path>
- octool validate-state <path>
- anything else?

**Comment by kelseyhightower** [comment]
@philips What about `octool lint`, which can help people avoid "doing it wrong"

**Comment by kunalkushwaha** [comment]
May be ``octool validate-security`` for  checking container security based on Capabilities and security policies, will be helpful.

**Comment by wking** [comment]
Has this been superseded by #109?  That issue is less targetted (it
also talks about validating runtime actions), but it seems to have
attracted more discussion.  In both cases, I'd rather leave config
validation be an external tool [1].  See also the existing work on
this in external tools [2].

[1]: https://github.com/opencontainers/specs/issues/109#issuecomment-130781950
[2]: https://groups.google.com/a/opencontainers.org/d/msg/dev/B2qQ9itIsgI/5fuFwSyYFAAJ
     Message-ID: <20150826212244.GB21585@odin.tremily.us>

**Comment by mrunalp** [comment]
We will move this code into github.com/opencontainers/ocitools

**Comment by vbatts** [comment]
https://github.com/opencontainers/ocitools and https://github.com/opencontainers/specs/tree/master/schema will address this kind of validation.

**Comment by vbatts** [comment]
We'll leave this open until 1.0, as a tracker that the validation tooling is sufficient.

**Comment by vbatts** [comment]
actually, closing in favor of the #219 tracker
